"""Initial migration

Revision ID: 805a18dee6b3
Revises: a188a4269d08
Create Date: 2026-01-19 10:40:55.601062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805a18dee6b3'
down_revision: Union[str, Sequence[str], None] = 'a188a4269d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'activity_category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Academic', 'Work', 'Health', 'Leisure', 'Personal', name='activitycategory'),
               existing_nullable=False)
    op.alter_column('outcome', 'outcome_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('exam_score', 'productivity_rating', 'mood_rating', 'weekly_self_review', name='outcometype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcome', 'outcome_type',
               existing_type=sa.Enum('exam_score', 'productivity_rating', 'mood_rating', 'weekly_self_review', name='outcometype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('activity', 'activity_category',
               existing_type=sa.Enum('Academic', 'Work', 'Health', 'Leisure', 'Personal', name='activitycategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
