"""Initial migration

Revision ID: 805a18dee6b3
Revises: a188a4269d08
Create Date: 2026-01-19 10:40:55.601062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805a18dee6b3'
down_revision: Union[str, Sequence[str], None] = 'a188a4269d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types manually if they don't exist
    op.execute("DO $$ BEGIN CREATE TYPE activitycategory AS ENUM ('Academic', 'Work', 'Health', 'Leisure', 'Personal'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE outcometype AS ENUM ('exam_score', 'productivity_rating', 'mood_rating', 'weekly_self_review'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    # Add missing columns to 'user' table
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])

    # Create missing chat_message table
    op.create_table('chat_message',
        sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=10), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
        sa.PrimaryKeyConstraint('message_id')
    )

    op.alter_column('activity', 'activity_category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Academic', 'Work', 'Health', 'Leisure', 'Personal', name='activitycategory'),
               existing_nullable=False,
               postgresql_using='activity_category::activitycategory')
    op.alter_column('outcome', 'outcome_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('exam_score', 'productivity_rating', 'mood_rating', 'weekly_self_review', name='outcometype'),
               existing_nullable=False,
               postgresql_using='outcome_type::outcometype')


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcome', 'outcome_type',
               existing_type=sa.Enum('exam_score', 'productivity_rating', 'mood_rating', 'weekly_self_review', name='outcometype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('activity', 'activity_category',
               existing_type=sa.Enum('Academic', 'Work', 'Health', 'Leisure', 'Personal', name='activitycategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
