"""describe your change

Revision ID: e3aba5779e77
Revises: 805a18dee6b3
Create Date: 2026-01-19 10:42:13.362618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3aba5779e77'
down_revision: Union[str, Sequence[str], None] = '805a18dee6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Redundant logic moved to 805a18dee6b3
    pass



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcome', 'outcome_type',
               existing_type=sa.Enum('exam_score', 'productivity_rating', 'mood_rating', 'weekly_self_review', name='outcometype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('activity', 'activity_category',
               existing_type=sa.Enum('Academic', 'Work', 'Health', 'Leisure', 'Personal', name='activitycategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
